# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - todo-dev-webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://tododevacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_64d3a9b909da41a1b636be4d27327cc4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_82d553a2c9724e31b5d9bf74af5c08bd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: tododevacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_64d3a9b909da41a1b636be4d27327cc4 }}/todo/webapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'todo-dev-webapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f115eb65637b48368c3e91987cb2999a }}
        images: 'tododevacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_64d3a9b909da41a1b636be4d27327cc4 }}/todo/webapp:${{ github.sha }}'